import "@/app/_styles/globals.css";
import Navbar from "./_components/Navbar";
import Link from "next/link";
import ClientProvider from "./_components/ClientProvider";
// import "./_styles/globals.css";

export const metadata = {
  title: "Data Science Club",
  // description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <Navbar />
        <ClientProvider>
          <main>{children}</main>
          <Link href="/chat">
            <button className="fixed bottom-4 right-4 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full shadow-lg">
              Chat with AI
            </button>
          </Link>
        </ClientProvider>
      </body>
    </html>
  );
}
